name: CI Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: test-${{ matrix.arch }}
    runs-on: ${{ (matrix.arch == 'arm64' && 'ubuntu-24.04-arm') || 'ubuntu-24.04' }}
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    
      # we use the composite action to install dependencies and setup the environment
      - name: Test default config
        uses: ./
        with:
          args: "--config=./config.yaml"

      - name: Build & test
        run: |
          go build .
          go test ./... -v

      # The previous step should have already installed the dependencies, so we can skip them here
      - name: Test no-dependencies
        uses: ./
        with:
          args: |
            --config=./config.yaml --cmd="/usr/bin/echo 'no-dependencies'"
          skip_dependencies: true

      # We provide a wrong kernel version `v700.4.293` to test the fail_on_validation feature
      - name: Test action fail_on_validation
        uses: ./
        id: test-fail
        with:
          args: |
            --config=./config.yaml --cmd="/usr/bin/echo 'fail'" --kernel_versions="v700.4.293,v5.10.237,v5.15.182"
          skip_dependencies: true
          fail_on_validation: false

      - name: Show report 
        run: cat ${{ steps.test-fail.outputs.report }}

      - name: Show outcome
        run: echo "${{ steps.test-fail.outputs.outcome }}"
