name: CI Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: test-x86
    runs-on: ubuntu-24.04
    steps:
      # todo!: install a fixed version of virtme-ng
      - name: Install vng
        run: |
          sudo apt update -y
          sudo apt install -y git qemu-kvm kmod virtiofsd udev virtme-ng

      - name: KVM support
        if: matrix.arch == 'amd64'
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Test vng
        run: |
          vng -v -r v5.4.293 -- /usr/bin/echo "OK"

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: Build & test
        run: |
          go build .
          go test ./...