name: Test composite action
on:
  pull_request:
  workflow_dispatch:    

jobs:
  test-composite-action:
    name: test-composite-action-${{ matrix.arch }}
    runs-on: ${{ (matrix.arch == 'arm64' && 'ubuntu-24.04-arm') || 'ubuntu-24.04' }}
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Test action
        uses: ./
        id: test
        with:
          cmd: "/usr/bin/echo 'OK'"
          kernels: "v5.4.293,v5.10.237,v5.15.182"
          kvm: ${{ matrix.arch == 'amd64' }}
          upload_report: "report-${{ matrix.arch }}.yaml"

      - name: Show report
        run: cat ${{ steps.test.outputs.report }}

  test-composite-action-no-upload:
    name: test-composite-action-no-upload
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Test action
        uses: ./
        id: test
        with:
          cmd: "/usr/bin/echo 'OK'"
          kernels: "v5.4.293,v5.10.237,v5.15.182"
          parallel: 2
          kvm: true

      - name: Show report
        run: cat ${{ steps.test.outputs.report }}